/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedToolConnectionsRouteImport } from './routes/_authenticated/tool-connections'
import { Route as AuthenticatedTelegramApprovalsRouteImport } from './routes/_authenticated/telegram-approvals'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedStrumentiProgettiRouteImport } from './routes/_authenticated/strumenti-progetti'
import { Route as AuthenticatedRunbooksRouteImport } from './routes/_authenticated/runbooks'
import { Route as AuthenticatedRoadmapRouteImport } from './routes/_authenticated/roadmap'
import { Route as AuthenticatedResultReviewRouteImport } from './routes/_authenticated/result-review'
import { Route as AuthenticatedProssimeAzioniRouteImport } from './routes/_authenticated/prossime-azioni'
import { Route as AuthenticatedProjectLoopRouteImport } from './routes/_authenticated/project-loop'
import { Route as AuthenticatedProjectConsoleRouteImport } from './routes/_authenticated/project-console'
import { Route as AuthenticatedProgettiRouteImport } from './routes/_authenticated/progetti'
import { Route as AuthenticatedOperatingDashboardRouteImport } from './routes/_authenticated/operating-dashboard'
import { Route as AuthenticatedN8nWorkflowsRouteImport } from './routes/_authenticated/n8n-workflows'
import { Route as AuthenticatedMvpFactoryRouteImport } from './routes/_authenticated/mvp-factory'
import { Route as AuthenticatedMasterSnapshotRouteImport } from './routes/_authenticated/master-snapshot'
import { Route as AuthenticatedLoopQaRouteImport } from './routes/_authenticated/loop-qa'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated/logs'
import { Route as AuthenticatedLiveRouteImport } from './routes/_authenticated/live'
import { Route as AuthenticatedKnowledgeMapRouteImport } from './routes/_authenticated/knowledge-map'
import { Route as AuthenticatedImpostazioniRouteImport } from './routes/_authenticated/impostazioni'
import { Route as AuthenticatedImportaRouteImport } from './routes/_authenticated/importa'
import { Route as AuthenticatedHealthCheckRouteImport } from './routes/_authenticated/health-check'
import { Route as AuthenticatedGuidaRouteImport } from './routes/_authenticated/guida'
import { Route as AuthenticatedGithubSyncRouteImport } from './routes/_authenticated/github-sync'
import { Route as AuthenticatedGithubOperationalRouteImport } from './routes/_authenticated/github-operational'
import { Route as AuthenticatedGithubCoverageRouteImport } from './routes/_authenticated/github-coverage'
import { Route as AuthenticatedFontiRouteImport } from './routes/_authenticated/fonti'
import { Route as AuthenticatedDriveKnowledgeRouteImport } from './routes/_authenticated/drive-knowledge'
import { Route as AuthenticatedConnettoriRouteImport } from './routes/_authenticated/connettori'
import { Route as AuthenticatedCompanyOsRouteImport } from './routes/_authenticated/company-os'
import { Route as AuthenticatedCompanyHomeRouteImport } from './routes/_authenticated/company-home'
import { Route as AuthenticatedCompanyBlueprintRouteImport } from './routes/_authenticated/company-blueprint'
import { Route as AuthenticatedCodeHandoffsRouteImport } from './routes/_authenticated/code-handoffs'
import { Route as AuthenticatedClipboardAiRouteImport } from './routes/_authenticated/clipboard-ai'
import { Route as AuthenticatedClientOnboardingRouteImport } from './routes/_authenticated/client-onboarding'
import { Route as AuthenticatedCalendarKnowledgeRouteImport } from './routes/_authenticated/calendar-knowledge'
import { Route as AuthenticatedBuildEnginesRouteImport } from './routes/_authenticated/build-engines'
import { Route as AuthenticatedAutomationReadinessRouteImport } from './routes/_authenticated/automation-readiness'
import { Route as AuthenticatedAutomationControlRouteImport } from './routes/_authenticated/automation-control'
import { Route as AuthenticatedArchivioRouteImport } from './routes/_authenticated/archivio'
import { Route as AuthenticatedAllineamentoRouteImport } from './routes/_authenticated/allineamento'
import { Route as AuthenticatedAgentsRouteImport } from './routes/_authenticated/agents'
import { Route as AuthenticatedAgentRunsRouteImport } from './routes/_authenticated/agent-runs'
import { Route as AuthenticatedAgentCenterRouteImport } from './routes/_authenticated/agent-center'
import { Route as AuthenticatedActionQueueRouteImport } from './routes/_authenticated/action-queue'
import { Route as AuthenticatedImportaIndexRouteImport } from './routes/_authenticated/importa.index'
import { Route as ApiPublicN8nPilotCallbackRouteImport } from './routes/api/public/n8n-pilot-callback'
import { Route as ApiPublicN8nCallbackRouteImport } from './routes/api/public/n8n-callback'
import { Route as AuthenticatedProgettiBrainIdRouteImport } from './routes/_authenticated/progetti.$brainId'
import { Route as AuthenticatedImportaPromptStoriciRouteImport } from './routes/_authenticated/importa.prompt-storici'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicDriveOauthCallbackRouteImport } from './routes/api/public/drive-oauth/callback'
import { Route as ApiPublicCalendarOauthCallbackRouteImport } from './routes/api/public/calendar-oauth/callback'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedToolConnectionsRoute =
  AuthenticatedToolConnectionsRouteImport.update({
    id: '/tool-connections',
    path: '/tool-connections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTelegramApprovalsRoute =
  AuthenticatedTelegramApprovalsRouteImport.update({
    id: '/telegram-approvals',
    path: '/telegram-approvals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStrumentiProgettiRoute =
  AuthenticatedStrumentiProgettiRouteImport.update({
    id: '/strumenti-progetti',
    path: '/strumenti-progetti',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRunbooksRoute = AuthenticatedRunbooksRouteImport.update({
  id: '/runbooks',
  path: '/runbooks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoadmapRoute = AuthenticatedRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResultReviewRoute =
  AuthenticatedResultReviewRouteImport.update({
    id: '/result-review',
    path: '/result-review',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProssimeAzioniRoute =
  AuthenticatedProssimeAzioniRouteImport.update({
    id: '/prossime-azioni',
    path: '/prossime-azioni',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectLoopRoute =
  AuthenticatedProjectLoopRouteImport.update({
    id: '/project-loop',
    path: '/project-loop',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectConsoleRoute =
  AuthenticatedProjectConsoleRouteImport.update({
    id: '/project-console',
    path: '/project-console',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProgettiRoute = AuthenticatedProgettiRouteImport.update({
  id: '/progetti',
  path: '/progetti',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOperatingDashboardRoute =
  AuthenticatedOperatingDashboardRouteImport.update({
    id: '/operating-dashboard',
    path: '/operating-dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedN8nWorkflowsRoute =
  AuthenticatedN8nWorkflowsRouteImport.update({
    id: '/n8n-workflows',
    path: '/n8n-workflows',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMvpFactoryRoute = AuthenticatedMvpFactoryRouteImport.update({
  id: '/mvp-factory',
  path: '/mvp-factory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMasterSnapshotRoute =
  AuthenticatedMasterSnapshotRouteImport.update({
    id: '/master-snapshot',
    path: '/master-snapshot',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLoopQaRoute = AuthenticatedLoopQaRouteImport.update({
  id: '/loop-qa',
  path: '/loop-qa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLiveRoute = AuthenticatedLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKnowledgeMapRoute =
  AuthenticatedKnowledgeMapRouteImport.update({
    id: '/knowledge-map',
    path: '/knowledge-map',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedImpostazioniRoute =
  AuthenticatedImpostazioniRouteImport.update({
    id: '/impostazioni',
    path: '/impostazioni',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedImportaRoute = AuthenticatedImportaRouteImport.update({
  id: '/importa',
  path: '/importa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHealthCheckRoute =
  AuthenticatedHealthCheckRouteImport.update({
    id: '/health-check',
    path: '/health-check',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGuidaRoute = AuthenticatedGuidaRouteImport.update({
  id: '/guida',
  path: '/guida',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGithubSyncRoute = AuthenticatedGithubSyncRouteImport.update({
  id: '/github-sync',
  path: '/github-sync',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGithubOperationalRoute =
  AuthenticatedGithubOperationalRouteImport.update({
    id: '/github-operational',
    path: '/github-operational',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGithubCoverageRoute =
  AuthenticatedGithubCoverageRouteImport.update({
    id: '/github-coverage',
    path: '/github-coverage',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFontiRoute = AuthenticatedFontiRouteImport.update({
  id: '/fonti',
  path: '/fonti',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDriveKnowledgeRoute =
  AuthenticatedDriveKnowledgeRouteImport.update({
    id: '/drive-knowledge',
    path: '/drive-knowledge',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConnettoriRoute = AuthenticatedConnettoriRouteImport.update({
  id: '/connettori',
  path: '/connettori',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompanyOsRoute = AuthenticatedCompanyOsRouteImport.update({
  id: '/company-os',
  path: '/company-os',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompanyHomeRoute =
  AuthenticatedCompanyHomeRouteImport.update({
    id: '/company-home',
    path: '/company-home',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompanyBlueprintRoute =
  AuthenticatedCompanyBlueprintRouteImport.update({
    id: '/company-blueprint',
    path: '/company-blueprint',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCodeHandoffsRoute =
  AuthenticatedCodeHandoffsRouteImport.update({
    id: '/code-handoffs',
    path: '/code-handoffs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClipboardAiRoute =
  AuthenticatedClipboardAiRouteImport.update({
    id: '/clipboard-ai',
    path: '/clipboard-ai',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientOnboardingRoute =
  AuthenticatedClientOnboardingRouteImport.update({
    id: '/client-onboarding',
    path: '/client-onboarding',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCalendarKnowledgeRoute =
  AuthenticatedCalendarKnowledgeRouteImport.update({
    id: '/calendar-knowledge',
    path: '/calendar-knowledge',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBuildEnginesRoute =
  AuthenticatedBuildEnginesRouteImport.update({
    id: '/build-engines',
    path: '/build-engines',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAutomationReadinessRoute =
  AuthenticatedAutomationReadinessRouteImport.update({
    id: '/automation-readiness',
    path: '/automation-readiness',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAutomationControlRoute =
  AuthenticatedAutomationControlRouteImport.update({
    id: '/automation-control',
    path: '/automation-control',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedArchivioRoute = AuthenticatedArchivioRouteImport.update({
  id: '/archivio',
  path: '/archivio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAllineamentoRoute =
  AuthenticatedAllineamentoRouteImport.update({
    id: '/allineamento',
    path: '/allineamento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgentsRoute = AuthenticatedAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgentRunsRoute = AuthenticatedAgentRunsRouteImport.update({
  id: '/agent-runs',
  path: '/agent-runs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgentCenterRoute =
  AuthenticatedAgentCenterRouteImport.update({
    id: '/agent-center',
    path: '/agent-center',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedActionQueueRoute =
  AuthenticatedActionQueueRouteImport.update({
    id: '/action-queue',
    path: '/action-queue',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedImportaIndexRoute =
  AuthenticatedImportaIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedImportaRoute,
  } as any)
const ApiPublicN8nPilotCallbackRoute =
  ApiPublicN8nPilotCallbackRouteImport.update({
    id: '/api/public/n8n-pilot-callback',
    path: '/api/public/n8n-pilot-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicN8nCallbackRoute = ApiPublicN8nCallbackRouteImport.update({
  id: '/api/public/n8n-callback',
  path: '/api/public/n8n-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProgettiBrainIdRoute =
  AuthenticatedProgettiBrainIdRouteImport.update({
    id: '/$brainId',
    path: '/$brainId',
    getParentRoute: () => AuthenticatedProgettiRoute,
  } as any)
const AuthenticatedImportaPromptStoriciRoute =
  AuthenticatedImportaPromptStoriciRouteImport.update({
    id: '/prompt-storici',
    path: '/prompt-storici',
    getParentRoute: () => AuthenticatedImportaRoute,
  } as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDriveOauthCallbackRoute =
  ApiPublicDriveOauthCallbackRouteImport.update({
    id: '/api/public/drive-oauth/callback',
    path: '/api/public/drive-oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCalendarOauthCallbackRoute =
  ApiPublicCalendarOauthCallbackRouteImport.update({
    id: '/api/public/calendar-oauth/callback',
    path: '/api/public/calendar-oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/action-queue': typeof AuthenticatedActionQueueRoute
  '/agent-center': typeof AuthenticatedAgentCenterRoute
  '/agent-runs': typeof AuthenticatedAgentRunsRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/allineamento': typeof AuthenticatedAllineamentoRoute
  '/archivio': typeof AuthenticatedArchivioRoute
  '/automation-control': typeof AuthenticatedAutomationControlRoute
  '/automation-readiness': typeof AuthenticatedAutomationReadinessRoute
  '/build-engines': typeof AuthenticatedBuildEnginesRoute
  '/calendar-knowledge': typeof AuthenticatedCalendarKnowledgeRoute
  '/client-onboarding': typeof AuthenticatedClientOnboardingRoute
  '/clipboard-ai': typeof AuthenticatedClipboardAiRoute
  '/code-handoffs': typeof AuthenticatedCodeHandoffsRoute
  '/company-blueprint': typeof AuthenticatedCompanyBlueprintRoute
  '/company-home': typeof AuthenticatedCompanyHomeRoute
  '/company-os': typeof AuthenticatedCompanyOsRoute
  '/connettori': typeof AuthenticatedConnettoriRoute
  '/drive-knowledge': typeof AuthenticatedDriveKnowledgeRoute
  '/fonti': typeof AuthenticatedFontiRoute
  '/github-coverage': typeof AuthenticatedGithubCoverageRoute
  '/github-operational': typeof AuthenticatedGithubOperationalRoute
  '/github-sync': typeof AuthenticatedGithubSyncRoute
  '/guida': typeof AuthenticatedGuidaRoute
  '/health-check': typeof AuthenticatedHealthCheckRoute
  '/importa': typeof AuthenticatedImportaRouteWithChildren
  '/impostazioni': typeof AuthenticatedImpostazioniRoute
  '/knowledge-map': typeof AuthenticatedKnowledgeMapRoute
  '/live': typeof AuthenticatedLiveRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/loop-qa': typeof AuthenticatedLoopQaRoute
  '/master-snapshot': typeof AuthenticatedMasterSnapshotRoute
  '/mvp-factory': typeof AuthenticatedMvpFactoryRoute
  '/n8n-workflows': typeof AuthenticatedN8nWorkflowsRoute
  '/operating-dashboard': typeof AuthenticatedOperatingDashboardRoute
  '/progetti': typeof AuthenticatedProgettiRouteWithChildren
  '/project-console': typeof AuthenticatedProjectConsoleRoute
  '/project-loop': typeof AuthenticatedProjectLoopRoute
  '/prossime-azioni': typeof AuthenticatedProssimeAzioniRoute
  '/result-review': typeof AuthenticatedResultReviewRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/runbooks': typeof AuthenticatedRunbooksRoute
  '/strumenti-progetti': typeof AuthenticatedStrumentiProgettiRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/telegram-approvals': typeof AuthenticatedTelegramApprovalsRoute
  '/tool-connections': typeof AuthenticatedToolConnectionsRoute
  '/importa/prompt-storici': typeof AuthenticatedImportaPromptStoriciRoute
  '/progetti/$brainId': typeof AuthenticatedProgettiBrainIdRoute
  '/api/public/n8n-callback': typeof ApiPublicN8nCallbackRoute
  '/api/public/n8n-pilot-callback': typeof ApiPublicN8nPilotCallbackRoute
  '/importa/': typeof AuthenticatedImportaIndexRoute
  '/api/public/calendar-oauth/callback': typeof ApiPublicCalendarOauthCallbackRoute
  '/api/public/drive-oauth/callback': typeof ApiPublicDriveOauthCallbackRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/action-queue': typeof AuthenticatedActionQueueRoute
  '/agent-center': typeof AuthenticatedAgentCenterRoute
  '/agent-runs': typeof AuthenticatedAgentRunsRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/allineamento': typeof AuthenticatedAllineamentoRoute
  '/archivio': typeof AuthenticatedArchivioRoute
  '/automation-control': typeof AuthenticatedAutomationControlRoute
  '/automation-readiness': typeof AuthenticatedAutomationReadinessRoute
  '/build-engines': typeof AuthenticatedBuildEnginesRoute
  '/calendar-knowledge': typeof AuthenticatedCalendarKnowledgeRoute
  '/client-onboarding': typeof AuthenticatedClientOnboardingRoute
  '/clipboard-ai': typeof AuthenticatedClipboardAiRoute
  '/code-handoffs': typeof AuthenticatedCodeHandoffsRoute
  '/company-blueprint': typeof AuthenticatedCompanyBlueprintRoute
  '/company-home': typeof AuthenticatedCompanyHomeRoute
  '/company-os': typeof AuthenticatedCompanyOsRoute
  '/connettori': typeof AuthenticatedConnettoriRoute
  '/drive-knowledge': typeof AuthenticatedDriveKnowledgeRoute
  '/fonti': typeof AuthenticatedFontiRoute
  '/github-coverage': typeof AuthenticatedGithubCoverageRoute
  '/github-operational': typeof AuthenticatedGithubOperationalRoute
  '/github-sync': typeof AuthenticatedGithubSyncRoute
  '/guida': typeof AuthenticatedGuidaRoute
  '/health-check': typeof AuthenticatedHealthCheckRoute
  '/impostazioni': typeof AuthenticatedImpostazioniRoute
  '/knowledge-map': typeof AuthenticatedKnowledgeMapRoute
  '/live': typeof AuthenticatedLiveRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/loop-qa': typeof AuthenticatedLoopQaRoute
  '/master-snapshot': typeof AuthenticatedMasterSnapshotRoute
  '/mvp-factory': typeof AuthenticatedMvpFactoryRoute
  '/n8n-workflows': typeof AuthenticatedN8nWorkflowsRoute
  '/operating-dashboard': typeof AuthenticatedOperatingDashboardRoute
  '/progetti': typeof AuthenticatedProgettiRouteWithChildren
  '/project-console': typeof AuthenticatedProjectConsoleRoute
  '/project-loop': typeof AuthenticatedProjectLoopRoute
  '/prossime-azioni': typeof AuthenticatedProssimeAzioniRoute
  '/result-review': typeof AuthenticatedResultReviewRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/runbooks': typeof AuthenticatedRunbooksRoute
  '/strumenti-progetti': typeof AuthenticatedStrumentiProgettiRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/telegram-approvals': typeof AuthenticatedTelegramApprovalsRoute
  '/tool-connections': typeof AuthenticatedToolConnectionsRoute
  '/': typeof AuthenticatedIndexRoute
  '/importa/prompt-storici': typeof AuthenticatedImportaPromptStoriciRoute
  '/progetti/$brainId': typeof AuthenticatedProgettiBrainIdRoute
  '/api/public/n8n-callback': typeof ApiPublicN8nCallbackRoute
  '/api/public/n8n-pilot-callback': typeof ApiPublicN8nPilotCallbackRoute
  '/importa': typeof AuthenticatedImportaIndexRoute
  '/api/public/calendar-oauth/callback': typeof ApiPublicCalendarOauthCallbackRoute
  '/api/public/drive-oauth/callback': typeof ApiPublicDriveOauthCallbackRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/action-queue': typeof AuthenticatedActionQueueRoute
  '/_authenticated/agent-center': typeof AuthenticatedAgentCenterRoute
  '/_authenticated/agent-runs': typeof AuthenticatedAgentRunsRoute
  '/_authenticated/agents': typeof AuthenticatedAgentsRoute
  '/_authenticated/allineamento': typeof AuthenticatedAllineamentoRoute
  '/_authenticated/archivio': typeof AuthenticatedArchivioRoute
  '/_authenticated/automation-control': typeof AuthenticatedAutomationControlRoute
  '/_authenticated/automation-readiness': typeof AuthenticatedAutomationReadinessRoute
  '/_authenticated/build-engines': typeof AuthenticatedBuildEnginesRoute
  '/_authenticated/calendar-knowledge': typeof AuthenticatedCalendarKnowledgeRoute
  '/_authenticated/client-onboarding': typeof AuthenticatedClientOnboardingRoute
  '/_authenticated/clipboard-ai': typeof AuthenticatedClipboardAiRoute
  '/_authenticated/code-handoffs': typeof AuthenticatedCodeHandoffsRoute
  '/_authenticated/company-blueprint': typeof AuthenticatedCompanyBlueprintRoute
  '/_authenticated/company-home': typeof AuthenticatedCompanyHomeRoute
  '/_authenticated/company-os': typeof AuthenticatedCompanyOsRoute
  '/_authenticated/connettori': typeof AuthenticatedConnettoriRoute
  '/_authenticated/drive-knowledge': typeof AuthenticatedDriveKnowledgeRoute
  '/_authenticated/fonti': typeof AuthenticatedFontiRoute
  '/_authenticated/github-coverage': typeof AuthenticatedGithubCoverageRoute
  '/_authenticated/github-operational': typeof AuthenticatedGithubOperationalRoute
  '/_authenticated/github-sync': typeof AuthenticatedGithubSyncRoute
  '/_authenticated/guida': typeof AuthenticatedGuidaRoute
  '/_authenticated/health-check': typeof AuthenticatedHealthCheckRoute
  '/_authenticated/importa': typeof AuthenticatedImportaRouteWithChildren
  '/_authenticated/impostazioni': typeof AuthenticatedImpostazioniRoute
  '/_authenticated/knowledge-map': typeof AuthenticatedKnowledgeMapRoute
  '/_authenticated/live': typeof AuthenticatedLiveRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/loop-qa': typeof AuthenticatedLoopQaRoute
  '/_authenticated/master-snapshot': typeof AuthenticatedMasterSnapshotRoute
  '/_authenticated/mvp-factory': typeof AuthenticatedMvpFactoryRoute
  '/_authenticated/n8n-workflows': typeof AuthenticatedN8nWorkflowsRoute
  '/_authenticated/operating-dashboard': typeof AuthenticatedOperatingDashboardRoute
  '/_authenticated/progetti': typeof AuthenticatedProgettiRouteWithChildren
  '/_authenticated/project-console': typeof AuthenticatedProjectConsoleRoute
  '/_authenticated/project-loop': typeof AuthenticatedProjectLoopRoute
  '/_authenticated/prossime-azioni': typeof AuthenticatedProssimeAzioniRoute
  '/_authenticated/result-review': typeof AuthenticatedResultReviewRoute
  '/_authenticated/roadmap': typeof AuthenticatedRoadmapRoute
  '/_authenticated/runbooks': typeof AuthenticatedRunbooksRoute
  '/_authenticated/strumenti-progetti': typeof AuthenticatedStrumentiProgettiRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/telegram-approvals': typeof AuthenticatedTelegramApprovalsRoute
  '/_authenticated/tool-connections': typeof AuthenticatedToolConnectionsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/importa/prompt-storici': typeof AuthenticatedImportaPromptStoriciRoute
  '/_authenticated/progetti/$brainId': typeof AuthenticatedProgettiBrainIdRoute
  '/api/public/n8n-callback': typeof ApiPublicN8nCallbackRoute
  '/api/public/n8n-pilot-callback': typeof ApiPublicN8nPilotCallbackRoute
  '/_authenticated/importa/': typeof AuthenticatedImportaIndexRoute
  '/api/public/calendar-oauth/callback': typeof ApiPublicCalendarOauthCallbackRoute
  '/api/public/drive-oauth/callback': typeof ApiPublicDriveOauthCallbackRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/action-queue'
    | '/agent-center'
    | '/agent-runs'
    | '/agents'
    | '/allineamento'
    | '/archivio'
    | '/automation-control'
    | '/automation-readiness'
    | '/build-engines'
    | '/calendar-knowledge'
    | '/client-onboarding'
    | '/clipboard-ai'
    | '/code-handoffs'
    | '/company-blueprint'
    | '/company-home'
    | '/company-os'
    | '/connettori'
    | '/drive-knowledge'
    | '/fonti'
    | '/github-coverage'
    | '/github-operational'
    | '/github-sync'
    | '/guida'
    | '/health-check'
    | '/importa'
    | '/impostazioni'
    | '/knowledge-map'
    | '/live'
    | '/logs'
    | '/loop-qa'
    | '/master-snapshot'
    | '/mvp-factory'
    | '/n8n-workflows'
    | '/operating-dashboard'
    | '/progetti'
    | '/project-console'
    | '/project-loop'
    | '/prossime-azioni'
    | '/result-review'
    | '/roadmap'
    | '/runbooks'
    | '/strumenti-progetti'
    | '/tasks'
    | '/telegram-approvals'
    | '/tool-connections'
    | '/importa/prompt-storici'
    | '/progetti/$brainId'
    | '/api/public/n8n-callback'
    | '/api/public/n8n-pilot-callback'
    | '/importa/'
    | '/api/public/calendar-oauth/callback'
    | '/api/public/drive-oauth/callback'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/action-queue'
    | '/agent-center'
    | '/agent-runs'
    | '/agents'
    | '/allineamento'
    | '/archivio'
    | '/automation-control'
    | '/automation-readiness'
    | '/build-engines'
    | '/calendar-knowledge'
    | '/client-onboarding'
    | '/clipboard-ai'
    | '/code-handoffs'
    | '/company-blueprint'
    | '/company-home'
    | '/company-os'
    | '/connettori'
    | '/drive-knowledge'
    | '/fonti'
    | '/github-coverage'
    | '/github-operational'
    | '/github-sync'
    | '/guida'
    | '/health-check'
    | '/impostazioni'
    | '/knowledge-map'
    | '/live'
    | '/logs'
    | '/loop-qa'
    | '/master-snapshot'
    | '/mvp-factory'
    | '/n8n-workflows'
    | '/operating-dashboard'
    | '/progetti'
    | '/project-console'
    | '/project-loop'
    | '/prossime-azioni'
    | '/result-review'
    | '/roadmap'
    | '/runbooks'
    | '/strumenti-progetti'
    | '/tasks'
    | '/telegram-approvals'
    | '/tool-connections'
    | '/'
    | '/importa/prompt-storici'
    | '/progetti/$brainId'
    | '/api/public/n8n-callback'
    | '/api/public/n8n-pilot-callback'
    | '/importa'
    | '/api/public/calendar-oauth/callback'
    | '/api/public/drive-oauth/callback'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/action-queue'
    | '/_authenticated/agent-center'
    | '/_authenticated/agent-runs'
    | '/_authenticated/agents'
    | '/_authenticated/allineamento'
    | '/_authenticated/archivio'
    | '/_authenticated/automation-control'
    | '/_authenticated/automation-readiness'
    | '/_authenticated/build-engines'
    | '/_authenticated/calendar-knowledge'
    | '/_authenticated/client-onboarding'
    | '/_authenticated/clipboard-ai'
    | '/_authenticated/code-handoffs'
    | '/_authenticated/company-blueprint'
    | '/_authenticated/company-home'
    | '/_authenticated/company-os'
    | '/_authenticated/connettori'
    | '/_authenticated/drive-knowledge'
    | '/_authenticated/fonti'
    | '/_authenticated/github-coverage'
    | '/_authenticated/github-operational'
    | '/_authenticated/github-sync'
    | '/_authenticated/guida'
    | '/_authenticated/health-check'
    | '/_authenticated/importa'
    | '/_authenticated/impostazioni'
    | '/_authenticated/knowledge-map'
    | '/_authenticated/live'
    | '/_authenticated/logs'
    | '/_authenticated/loop-qa'
    | '/_authenticated/master-snapshot'
    | '/_authenticated/mvp-factory'
    | '/_authenticated/n8n-workflows'
    | '/_authenticated/operating-dashboard'
    | '/_authenticated/progetti'
    | '/_authenticated/project-console'
    | '/_authenticated/project-loop'
    | '/_authenticated/prossime-azioni'
    | '/_authenticated/result-review'
    | '/_authenticated/roadmap'
    | '/_authenticated/runbooks'
    | '/_authenticated/strumenti-progetti'
    | '/_authenticated/tasks'
    | '/_authenticated/telegram-approvals'
    | '/_authenticated/tool-connections'
    | '/_authenticated/'
    | '/_authenticated/importa/prompt-storici'
    | '/_authenticated/progetti/$brainId'
    | '/api/public/n8n-callback'
    | '/api/public/n8n-pilot-callback'
    | '/_authenticated/importa/'
    | '/api/public/calendar-oauth/callback'
    | '/api/public/drive-oauth/callback'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicN8nCallbackRoute: typeof ApiPublicN8nCallbackRoute
  ApiPublicN8nPilotCallbackRoute: typeof ApiPublicN8nPilotCallbackRoute
  ApiPublicCalendarOauthCallbackRoute: typeof ApiPublicCalendarOauthCallbackRoute
  ApiPublicDriveOauthCallbackRoute: typeof ApiPublicDriveOauthCallbackRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tool-connections': {
      id: '/_authenticated/tool-connections'
      path: '/tool-connections'
      fullPath: '/tool-connections'
      preLoaderRoute: typeof AuthenticatedToolConnectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/telegram-approvals': {
      id: '/_authenticated/telegram-approvals'
      path: '/telegram-approvals'
      fullPath: '/telegram-approvals'
      preLoaderRoute: typeof AuthenticatedTelegramApprovalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/strumenti-progetti': {
      id: '/_authenticated/strumenti-progetti'
      path: '/strumenti-progetti'
      fullPath: '/strumenti-progetti'
      preLoaderRoute: typeof AuthenticatedStrumentiProgettiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/runbooks': {
      id: '/_authenticated/runbooks'
      path: '/runbooks'
      fullPath: '/runbooks'
      preLoaderRoute: typeof AuthenticatedRunbooksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roadmap': {
      id: '/_authenticated/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof AuthenticatedRoadmapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/result-review': {
      id: '/_authenticated/result-review'
      path: '/result-review'
      fullPath: '/result-review'
      preLoaderRoute: typeof AuthenticatedResultReviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prossime-azioni': {
      id: '/_authenticated/prossime-azioni'
      path: '/prossime-azioni'
      fullPath: '/prossime-azioni'
      preLoaderRoute: typeof AuthenticatedProssimeAzioniRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/project-loop': {
      id: '/_authenticated/project-loop'
      path: '/project-loop'
      fullPath: '/project-loop'
      preLoaderRoute: typeof AuthenticatedProjectLoopRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/project-console': {
      id: '/_authenticated/project-console'
      path: '/project-console'
      fullPath: '/project-console'
      preLoaderRoute: typeof AuthenticatedProjectConsoleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/progetti': {
      id: '/_authenticated/progetti'
      path: '/progetti'
      fullPath: '/progetti'
      preLoaderRoute: typeof AuthenticatedProgettiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operating-dashboard': {
      id: '/_authenticated/operating-dashboard'
      path: '/operating-dashboard'
      fullPath: '/operating-dashboard'
      preLoaderRoute: typeof AuthenticatedOperatingDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/n8n-workflows': {
      id: '/_authenticated/n8n-workflows'
      path: '/n8n-workflows'
      fullPath: '/n8n-workflows'
      preLoaderRoute: typeof AuthenticatedN8nWorkflowsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mvp-factory': {
      id: '/_authenticated/mvp-factory'
      path: '/mvp-factory'
      fullPath: '/mvp-factory'
      preLoaderRoute: typeof AuthenticatedMvpFactoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/master-snapshot': {
      id: '/_authenticated/master-snapshot'
      path: '/master-snapshot'
      fullPath: '/master-snapshot'
      preLoaderRoute: typeof AuthenticatedMasterSnapshotRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/loop-qa': {
      id: '/_authenticated/loop-qa'
      path: '/loop-qa'
      fullPath: '/loop-qa'
      preLoaderRoute: typeof AuthenticatedLoopQaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/live': {
      id: '/_authenticated/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof AuthenticatedLiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge-map': {
      id: '/_authenticated/knowledge-map'
      path: '/knowledge-map'
      fullPath: '/knowledge-map'
      preLoaderRoute: typeof AuthenticatedKnowledgeMapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/impostazioni': {
      id: '/_authenticated/impostazioni'
      path: '/impostazioni'
      fullPath: '/impostazioni'
      preLoaderRoute: typeof AuthenticatedImpostazioniRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/importa': {
      id: '/_authenticated/importa'
      path: '/importa'
      fullPath: '/importa'
      preLoaderRoute: typeof AuthenticatedImportaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/health-check': {
      id: '/_authenticated/health-check'
      path: '/health-check'
      fullPath: '/health-check'
      preLoaderRoute: typeof AuthenticatedHealthCheckRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guida': {
      id: '/_authenticated/guida'
      path: '/guida'
      fullPath: '/guida'
      preLoaderRoute: typeof AuthenticatedGuidaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/github-sync': {
      id: '/_authenticated/github-sync'
      path: '/github-sync'
      fullPath: '/github-sync'
      preLoaderRoute: typeof AuthenticatedGithubSyncRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/github-operational': {
      id: '/_authenticated/github-operational'
      path: '/github-operational'
      fullPath: '/github-operational'
      preLoaderRoute: typeof AuthenticatedGithubOperationalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/github-coverage': {
      id: '/_authenticated/github-coverage'
      path: '/github-coverage'
      fullPath: '/github-coverage'
      preLoaderRoute: typeof AuthenticatedGithubCoverageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fonti': {
      id: '/_authenticated/fonti'
      path: '/fonti'
      fullPath: '/fonti'
      preLoaderRoute: typeof AuthenticatedFontiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/drive-knowledge': {
      id: '/_authenticated/drive-knowledge'
      path: '/drive-knowledge'
      fullPath: '/drive-knowledge'
      preLoaderRoute: typeof AuthenticatedDriveKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/connettori': {
      id: '/_authenticated/connettori'
      path: '/connettori'
      fullPath: '/connettori'
      preLoaderRoute: typeof AuthenticatedConnettoriRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/company-os': {
      id: '/_authenticated/company-os'
      path: '/company-os'
      fullPath: '/company-os'
      preLoaderRoute: typeof AuthenticatedCompanyOsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/company-home': {
      id: '/_authenticated/company-home'
      path: '/company-home'
      fullPath: '/company-home'
      preLoaderRoute: typeof AuthenticatedCompanyHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/company-blueprint': {
      id: '/_authenticated/company-blueprint'
      path: '/company-blueprint'
      fullPath: '/company-blueprint'
      preLoaderRoute: typeof AuthenticatedCompanyBlueprintRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/code-handoffs': {
      id: '/_authenticated/code-handoffs'
      path: '/code-handoffs'
      fullPath: '/code-handoffs'
      preLoaderRoute: typeof AuthenticatedCodeHandoffsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clipboard-ai': {
      id: '/_authenticated/clipboard-ai'
      path: '/clipboard-ai'
      fullPath: '/clipboard-ai'
      preLoaderRoute: typeof AuthenticatedClipboardAiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client-onboarding': {
      id: '/_authenticated/client-onboarding'
      path: '/client-onboarding'
      fullPath: '/client-onboarding'
      preLoaderRoute: typeof AuthenticatedClientOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar-knowledge': {
      id: '/_authenticated/calendar-knowledge'
      path: '/calendar-knowledge'
      fullPath: '/calendar-knowledge'
      preLoaderRoute: typeof AuthenticatedCalendarKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/build-engines': {
      id: '/_authenticated/build-engines'
      path: '/build-engines'
      fullPath: '/build-engines'
      preLoaderRoute: typeof AuthenticatedBuildEnginesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automation-readiness': {
      id: '/_authenticated/automation-readiness'
      path: '/automation-readiness'
      fullPath: '/automation-readiness'
      preLoaderRoute: typeof AuthenticatedAutomationReadinessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automation-control': {
      id: '/_authenticated/automation-control'
      path: '/automation-control'
      fullPath: '/automation-control'
      preLoaderRoute: typeof AuthenticatedAutomationControlRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/archivio': {
      id: '/_authenticated/archivio'
      path: '/archivio'
      fullPath: '/archivio'
      preLoaderRoute: typeof AuthenticatedArchivioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/allineamento': {
      id: '/_authenticated/allineamento'
      path: '/allineamento'
      fullPath: '/allineamento'
      preLoaderRoute: typeof AuthenticatedAllineamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agents': {
      id: '/_authenticated/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthenticatedAgentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agent-runs': {
      id: '/_authenticated/agent-runs'
      path: '/agent-runs'
      fullPath: '/agent-runs'
      preLoaderRoute: typeof AuthenticatedAgentRunsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agent-center': {
      id: '/_authenticated/agent-center'
      path: '/agent-center'
      fullPath: '/agent-center'
      preLoaderRoute: typeof AuthenticatedAgentCenterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/action-queue': {
      id: '/_authenticated/action-queue'
      path: '/action-queue'
      fullPath: '/action-queue'
      preLoaderRoute: typeof AuthenticatedActionQueueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/importa/': {
      id: '/_authenticated/importa/'
      path: '/'
      fullPath: '/importa/'
      preLoaderRoute: typeof AuthenticatedImportaIndexRouteImport
      parentRoute: typeof AuthenticatedImportaRoute
    }
    '/api/public/n8n-pilot-callback': {
      id: '/api/public/n8n-pilot-callback'
      path: '/api/public/n8n-pilot-callback'
      fullPath: '/api/public/n8n-pilot-callback'
      preLoaderRoute: typeof ApiPublicN8nPilotCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/n8n-callback': {
      id: '/api/public/n8n-callback'
      path: '/api/public/n8n-callback'
      fullPath: '/api/public/n8n-callback'
      preLoaderRoute: typeof ApiPublicN8nCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/progetti/$brainId': {
      id: '/_authenticated/progetti/$brainId'
      path: '/$brainId'
      fullPath: '/progetti/$brainId'
      preLoaderRoute: typeof AuthenticatedProgettiBrainIdRouteImport
      parentRoute: typeof AuthenticatedProgettiRoute
    }
    '/_authenticated/importa/prompt-storici': {
      id: '/_authenticated/importa/prompt-storici'
      path: '/prompt-storici'
      fullPath: '/importa/prompt-storici'
      preLoaderRoute: typeof AuthenticatedImportaPromptStoriciRouteImport
      parentRoute: typeof AuthenticatedImportaRoute
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/drive-oauth/callback': {
      id: '/api/public/drive-oauth/callback'
      path: '/api/public/drive-oauth/callback'
      fullPath: '/api/public/drive-oauth/callback'
      preLoaderRoute: typeof ApiPublicDriveOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/calendar-oauth/callback': {
      id: '/api/public/calendar-oauth/callback'
      path: '/api/public/calendar-oauth/callback'
      fullPath: '/api/public/calendar-oauth/callback'
      preLoaderRoute: typeof ApiPublicCalendarOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedImportaRouteChildren {
  AuthenticatedImportaPromptStoriciRoute: typeof AuthenticatedImportaPromptStoriciRoute
  AuthenticatedImportaIndexRoute: typeof AuthenticatedImportaIndexRoute
}

const AuthenticatedImportaRouteChildren: AuthenticatedImportaRouteChildren = {
  AuthenticatedImportaPromptStoriciRoute:
    AuthenticatedImportaPromptStoriciRoute,
  AuthenticatedImportaIndexRoute: AuthenticatedImportaIndexRoute,
}

const AuthenticatedImportaRouteWithChildren =
  AuthenticatedImportaRoute._addFileChildren(AuthenticatedImportaRouteChildren)

interface AuthenticatedProgettiRouteChildren {
  AuthenticatedProgettiBrainIdRoute: typeof AuthenticatedProgettiBrainIdRoute
}

const AuthenticatedProgettiRouteChildren: AuthenticatedProgettiRouteChildren = {
  AuthenticatedProgettiBrainIdRoute: AuthenticatedProgettiBrainIdRoute,
}

const AuthenticatedProgettiRouteWithChildren =
  AuthenticatedProgettiRoute._addFileChildren(
    AuthenticatedProgettiRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActionQueueRoute: typeof AuthenticatedActionQueueRoute
  AuthenticatedAgentCenterRoute: typeof AuthenticatedAgentCenterRoute
  AuthenticatedAgentRunsRoute: typeof AuthenticatedAgentRunsRoute
  AuthenticatedAgentsRoute: typeof AuthenticatedAgentsRoute
  AuthenticatedAllineamentoRoute: typeof AuthenticatedAllineamentoRoute
  AuthenticatedArchivioRoute: typeof AuthenticatedArchivioRoute
  AuthenticatedAutomationControlRoute: typeof AuthenticatedAutomationControlRoute
  AuthenticatedAutomationReadinessRoute: typeof AuthenticatedAutomationReadinessRoute
  AuthenticatedBuildEnginesRoute: typeof AuthenticatedBuildEnginesRoute
  AuthenticatedCalendarKnowledgeRoute: typeof AuthenticatedCalendarKnowledgeRoute
  AuthenticatedClientOnboardingRoute: typeof AuthenticatedClientOnboardingRoute
  AuthenticatedClipboardAiRoute: typeof AuthenticatedClipboardAiRoute
  AuthenticatedCodeHandoffsRoute: typeof AuthenticatedCodeHandoffsRoute
  AuthenticatedCompanyBlueprintRoute: typeof AuthenticatedCompanyBlueprintRoute
  AuthenticatedCompanyHomeRoute: typeof AuthenticatedCompanyHomeRoute
  AuthenticatedCompanyOsRoute: typeof AuthenticatedCompanyOsRoute
  AuthenticatedConnettoriRoute: typeof AuthenticatedConnettoriRoute
  AuthenticatedDriveKnowledgeRoute: typeof AuthenticatedDriveKnowledgeRoute
  AuthenticatedFontiRoute: typeof AuthenticatedFontiRoute
  AuthenticatedGithubCoverageRoute: typeof AuthenticatedGithubCoverageRoute
  AuthenticatedGithubOperationalRoute: typeof AuthenticatedGithubOperationalRoute
  AuthenticatedGithubSyncRoute: typeof AuthenticatedGithubSyncRoute
  AuthenticatedGuidaRoute: typeof AuthenticatedGuidaRoute
  AuthenticatedHealthCheckRoute: typeof AuthenticatedHealthCheckRoute
  AuthenticatedImportaRoute: typeof AuthenticatedImportaRouteWithChildren
  AuthenticatedImpostazioniRoute: typeof AuthenticatedImpostazioniRoute
  AuthenticatedKnowledgeMapRoute: typeof AuthenticatedKnowledgeMapRoute
  AuthenticatedLiveRoute: typeof AuthenticatedLiveRoute
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedLoopQaRoute: typeof AuthenticatedLoopQaRoute
  AuthenticatedMasterSnapshotRoute: typeof AuthenticatedMasterSnapshotRoute
  AuthenticatedMvpFactoryRoute: typeof AuthenticatedMvpFactoryRoute
  AuthenticatedN8nWorkflowsRoute: typeof AuthenticatedN8nWorkflowsRoute
  AuthenticatedOperatingDashboardRoute: typeof AuthenticatedOperatingDashboardRoute
  AuthenticatedProgettiRoute: typeof AuthenticatedProgettiRouteWithChildren
  AuthenticatedProjectConsoleRoute: typeof AuthenticatedProjectConsoleRoute
  AuthenticatedProjectLoopRoute: typeof AuthenticatedProjectLoopRoute
  AuthenticatedProssimeAzioniRoute: typeof AuthenticatedProssimeAzioniRoute
  AuthenticatedResultReviewRoute: typeof AuthenticatedResultReviewRoute
  AuthenticatedRoadmapRoute: typeof AuthenticatedRoadmapRoute
  AuthenticatedRunbooksRoute: typeof AuthenticatedRunbooksRoute
  AuthenticatedStrumentiProgettiRoute: typeof AuthenticatedStrumentiProgettiRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedTelegramApprovalsRoute: typeof AuthenticatedTelegramApprovalsRoute
  AuthenticatedToolConnectionsRoute: typeof AuthenticatedToolConnectionsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActionQueueRoute: AuthenticatedActionQueueRoute,
  AuthenticatedAgentCenterRoute: AuthenticatedAgentCenterRoute,
  AuthenticatedAgentRunsRoute: AuthenticatedAgentRunsRoute,
  AuthenticatedAgentsRoute: AuthenticatedAgentsRoute,
  AuthenticatedAllineamentoRoute: AuthenticatedAllineamentoRoute,
  AuthenticatedArchivioRoute: AuthenticatedArchivioRoute,
  AuthenticatedAutomationControlRoute: AuthenticatedAutomationControlRoute,
  AuthenticatedAutomationReadinessRoute: AuthenticatedAutomationReadinessRoute,
  AuthenticatedBuildEnginesRoute: AuthenticatedBuildEnginesRoute,
  AuthenticatedCalendarKnowledgeRoute: AuthenticatedCalendarKnowledgeRoute,
  AuthenticatedClientOnboardingRoute: AuthenticatedClientOnboardingRoute,
  AuthenticatedClipboardAiRoute: AuthenticatedClipboardAiRoute,
  AuthenticatedCodeHandoffsRoute: AuthenticatedCodeHandoffsRoute,
  AuthenticatedCompanyBlueprintRoute: AuthenticatedCompanyBlueprintRoute,
  AuthenticatedCompanyHomeRoute: AuthenticatedCompanyHomeRoute,
  AuthenticatedCompanyOsRoute: AuthenticatedCompanyOsRoute,
  AuthenticatedConnettoriRoute: AuthenticatedConnettoriRoute,
  AuthenticatedDriveKnowledgeRoute: AuthenticatedDriveKnowledgeRoute,
  AuthenticatedFontiRoute: AuthenticatedFontiRoute,
  AuthenticatedGithubCoverageRoute: AuthenticatedGithubCoverageRoute,
  AuthenticatedGithubOperationalRoute: AuthenticatedGithubOperationalRoute,
  AuthenticatedGithubSyncRoute: AuthenticatedGithubSyncRoute,
  AuthenticatedGuidaRoute: AuthenticatedGuidaRoute,
  AuthenticatedHealthCheckRoute: AuthenticatedHealthCheckRoute,
  AuthenticatedImportaRoute: AuthenticatedImportaRouteWithChildren,
  AuthenticatedImpostazioniRoute: AuthenticatedImpostazioniRoute,
  AuthenticatedKnowledgeMapRoute: AuthenticatedKnowledgeMapRoute,
  AuthenticatedLiveRoute: AuthenticatedLiveRoute,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedLoopQaRoute: AuthenticatedLoopQaRoute,
  AuthenticatedMasterSnapshotRoute: AuthenticatedMasterSnapshotRoute,
  AuthenticatedMvpFactoryRoute: AuthenticatedMvpFactoryRoute,
  AuthenticatedN8nWorkflowsRoute: AuthenticatedN8nWorkflowsRoute,
  AuthenticatedOperatingDashboardRoute: AuthenticatedOperatingDashboardRoute,
  AuthenticatedProgettiRoute: AuthenticatedProgettiRouteWithChildren,
  AuthenticatedProjectConsoleRoute: AuthenticatedProjectConsoleRoute,
  AuthenticatedProjectLoopRoute: AuthenticatedProjectLoopRoute,
  AuthenticatedProssimeAzioniRoute: AuthenticatedProssimeAzioniRoute,
  AuthenticatedResultReviewRoute: AuthenticatedResultReviewRoute,
  AuthenticatedRoadmapRoute: AuthenticatedRoadmapRoute,
  AuthenticatedRunbooksRoute: AuthenticatedRunbooksRoute,
  AuthenticatedStrumentiProgettiRoute: AuthenticatedStrumentiProgettiRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedTelegramApprovalsRoute: AuthenticatedTelegramApprovalsRoute,
  AuthenticatedToolConnectionsRoute: AuthenticatedToolConnectionsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicN8nCallbackRoute: ApiPublicN8nCallbackRoute,
  ApiPublicN8nPilotCallbackRoute: ApiPublicN8nPilotCallbackRoute,
  ApiPublicCalendarOauthCallbackRoute: ApiPublicCalendarOauthCallbackRoute,
  ApiPublicDriveOauthCallbackRoute: ApiPublicDriveOauthCallbackRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
